import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import './globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  sidenav,
  offers
}: Readonly<{
  children: React.ReactNode,
  sidenav: React.ReactNode,
  offers: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="sidenav" 
        style={{display:"inline"}}>
          Side Nav
          {sidenav}
         </div>
        <div style={{display : "inline"}}> 
            {children}
        </div>
        <div>
          {offers}
        </div>
      </body>
    </html>
  );
}
